import AdminGuardPageHandler from "@/components/admin/adminGuardPageHandler"
import AdminHeader from "@/components/admin/adminHeader"

export const metadata = {
  title: 'Admin Guard - Next',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <AdminGuardPageHandler>
          <AdminHeader />
          {children}
        </AdminGuardPageHandler>
      </body>
    </html>
  )
}
