CREATE TABLE users (
  id INT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(80) NOT NULL,
  password VARCHAR(80) NOT NULL,
  email VARCHAR(80) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
